version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - app-network
    volumes:
      - zookeeper_data:/var/lib/zookeeper

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network
    volumes:
      - kafka_data:/var/lib/kafka/data

  mysql-goservice:
    image: mysql:8.0
    container_name: mysql-go
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - mysql_go_data:/var/lib/mysql

  mysql-javaservice:
    image: mysql:8.0
    container_name: mysql-java
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: java_db
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
    networks:
      - app-network
    volumes:
      - mysql_java_data:/var/lib/mysql

  go-service:
    build:
      context: ./fc-wallet-core
      dockerfile: Dockerfile
    container_name: go-service
    depends_on:
      - kafka
      - mysql-goservice
    environment:
      KAFKA_BROKER: kafka:9092
      DB_HOST: mysql-go
      DB_PORT: 3306
      DB_NAME: wallet
      DB_PASSWORD: go_password
    networks:
      - app-network
    volumes:
      - go_data:/app/data

  java-service:
    build:
      context: ./fc-wallet-balance
      dockerfile: Dockerfile
    container_name: java-service
    depends_on:
      - kafka
      - mysql-javaservice
    environment:
      KAFKA_BROKER: kafka:9092
      DB_HOST: mysql-java
      DB_PORT: 3306
      DB_NAME: java_db
      DB_PASSWORD: root
    networks:
      - app-network
    volumes:
      - java_data:/app/data

networks:
  app-network:
    driver: bridge

volumes:
  zookeeper_data:
  kafka_data:
  mysql_go_data:
  mysql_java_data:
  go_data:
  java_data:
