
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@d.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "75f1ca1b-a6c5-4e5e-84f6-e2a17f3f0d04"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "1b94b998-1f92-4897-a5e2-24bde6685b5d",
    "account_id_to": "bb835285-769c-439f-b1cb-a8788bdf8e72",
    "amount": 25
}