
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@d.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "75f1ca1b-a6c5-4e5e-84f6-e2a17f3f0d04"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "7b18c3dc-1c1b-4930-8e2d-cd152047956f",
    "account_id_to": "61abb3d4-e922-42dc-aae3-9952a89894bb",
    "amount": 25
}